# Generated by Django 3.1.7 on 2021-04-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20210303_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='totalTime',
            field=models.CharField(default='0.0', max_length=100),
        ),
    ]
