# Generated by Django 3.1.7 on 2021-04-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_recipe_totaltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredientsDetail',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
