# Generated by Django 3.1.7 on 2021-05-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210413_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pseudo',
            field=models.CharField(default='pseudo', max_length=100),
        ),
    ]
