# Generated by Django 3.1.7 on 2021-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210510_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='user_favorite', to='service.Recipe'),
        ),
    ]
