# Generated by Django 3.1.7 on 2021-06-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_recipe_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(null=True, related_name='user_favorite', to='service.Recipe'),
        ),
    ]
