# Generated by Django 3.1.7 on 2021-06-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20210613_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('createdBy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('topic_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.topic')),
                ('user_related', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message', to='service.user')),
            ],
        ),
    ]
