# Generated by Django 3.1.7 on 2021-06-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_message_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='createdBy',
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='topic_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='service.topic'),
        ),
    ]
