# Generated by Django 3.1.7 on 2021-06-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20210617_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_related',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='topic_related',
            new_name='topic_id',
        ),
    ]
