# Generated by Django 3.1.7 on 2021-06-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_recipe_moderate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='moderate',
            field=models.BooleanField(default=True),
        ),
    ]
