# Generated by Django 3.1.7 on 2021-06-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20210618_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='stepList',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredientsDetail',
            field=models.JSONField(default=dict),
        ),
    ]
