# Generated by Django 3.1.7 on 2021-06-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_auto_20210621_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
